name: photobooth_flutter
description: "AI Photobooth application built with Flutter"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  camera: ^0.11.0+1
  camera_macos: ^0.0.9
  camera_platform_interface: ^2.7.0
  camera_windows: ^0.2.6+2
  crypto: ^3.0.6
  file_picker: ^9.2.1
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  flutter_secure_storage: ^9.2.4
  http: ^1.3.0
  image: ^4.5.4
  lottie: ^3.3.1
  path: ^1.9.0
  path_provider: ^2.1.5
  provider: ^6.1.2
  qr_flutter: ^4.1.0
  shared_preferences: ^2.5.2
  supabase_flutter: null
  video_player: null
  video_player_media_kit: ^1.0.6

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/characters/
    - assets/videos/
    - lib/api/ghibli.json
    - lib/api/faceswap.json
    - lib/api/pixar.json
    - lib/api/snoopy.json

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Black.otf
          weight: 900
        - asset: assets/fonts/Satoshi-Bold.otf
          weight: 700
        - asset: assets/fonts/Satoshi-Italic.otf
          weight: 500
        - asset: assets/fonts/Satoshi-Light.otf
          weight: 400
        - asset: assets/fonts/Satoshi-Medium.otf
          weight: 600
        - asset: assets/fonts/Satoshi-Regular.otf
          weight: 500
